
project_id = "natjhcqynqziccssnwim"
[[functions]]
verify_jwt = false
name = "wysiwyg-ai"
path = "supabase/functions/wysiwyg-ai"

[[functions]]
verify_jwt = false
name = "wysiwyg-ai-logs"
path = "supabase/functions/wysiwyg-ai-logs"

[[functions]]
verify_jwt = false
name = "register-trial"
path = "supabase/functions/register-trial"

[[functions]]
verify_jwt = false
name = "expire-trials"
path = "supabase/functions/expire-trials"

[[functions]]
verify_jwt = true
name = "create-checkout"
path = "supabase/functions/create-checkout"

[[functions]]
verify_jwt = true
name = "check-subscription"
path = "supabase/functions/check-subscription"

[[functions]]
verify_jwt = true
name = "customer-portal"
path = "supabase/functions/customer-portal"
