
project_id = "natjhcqynqziccssnwim"
[[functions]]
verify_jwt = false
name = "wysiwyg-ai"
path = "supabase/functions/wysiwyg-ai"

[[functions]]
verify_jwt = false
name = "wysiwyg-ai-logs"
path = "supabase/functions/wysiwyg-ai-logs"
