
# This file is managed by Lovable.
project_id = "natjhcqynqziccssnwim"

[functions.ftp-connect]
verify_jwt = true

[functions.ftp-download-file]
verify_jwt = true

[functions.ftp-list-directory]
verify_jwt = true

[functions.ftp-test-connection]
verify_jwt = true

[functions.ftp-get-file]
verify_jwt = true

[functions.ftp-list]
verify_jwt = true

[functions.send-email]
verify_jwt = true
